import { Language, PlayFormat } from "./Enums";

/**
 * The Identifiers data model describes a list of identifiers associated to a card.
 */
export interface Identifiers {
  /** The Card Kingdom card foil identifier. */
  cardKingdomFoilId?: string;

  /** The Card Kingdom card identifier. */
  cardKingdomId?: string;

  /** The Card Market card identifier. */
  mcmId?: string;

  /** The Card Market card meta identifier. */
  mcmMetaId?: string;

  /** The Magic: The Gathering Arena card identifier. */
  mtgArenaId?: string;

  /** The universal unique identifier generated by MTGJSON. Each entry is unique. Entries are for MTGJSON v4 uuid generation. */
  mtgjsonV4Id?: string;

  /** The Magic: The Gathering Online card foil identifier. */
  mtgoFoilId?: string;

  /** The Magic: The Gathering Online card identifier. */
  mtgoId?: string;

  /** The Wizards of the Coast card identifier used in conjunction with Gatherer. */
  multiverseId?: string;

  /** The universal unique identifier generated by Scryfall. Note that cards with multiple faces are not unique. */
  scryfallId?: string;

  /** The unique identifier generated by Scryfall for the card artwork that remains consistent across reprints. Newly spoiled cards may not have this field yet. */
  scryfallIllustrationId?: string;

  /** The unique identifier generated by Scryfall for this card's oracle identity. This value is consistent across reprinted card editions, and unique among different cards with the same name (tokens, Unstable variants, etc). */
  scryfallOracleId?: string;

  /** The TCGplayer card identifier. */
  tcgplayerProductId?: string;
}

/**
 * The Identifiers data model describes a list of identifiers associated to a card.
 */
export interface ForeignData {
  /* The name on the face of the card. */
  faceName?: string;

  /* The flavor text of the card. */
  flavorText?: string;

  /* The foreign language of card. */
  language: Language;

  /* The multiverse identifier of the card. */
  multiverseId?: string;

  /* The name of the card. */
  name: string;

  /* The text ruling of the card. */
  text?: string;

  /* The type of the card. Includes any supertypes and subtypes. */
  type?: string;
}

/**
 * The Legalities data model describes a list of legalities in play formats for a specific card.
 */
export type Legalities = {
  [Property in PlayFormat]?: boolean;
};

/**
 * The Rulings data model describes a list of rulings for a specific card.
 */
export interface Rulings {
  /** The release date in ISO 8601 format for the rule. */
  date?: string;

  /** The text ruling of the card. */
  text?: string;
}

/**
 * The Purchase Urls data model describes url paths to purchase a product from a marketplace.
 */
export interface PurchaseUrls {
  /** The URL to purchase a product on Card Kingdom. */
  cardKingdom?: string;

  /** The URL to purchase a foil product on Card Kingdom. */
  cardKingdomFoil?: string;

  /** The URL to purchase a product on Cardmarket. */
  cardmarket?: string;

  /** The URL to purchase a product on TCGplayer. */
  tcgplayer?: string;
}

/**
 * The Leadership Skills data model describes a list of formats that a specific card is legal to be your Commander in play formats that utilize commanders.
 */
export interface LeadershipSkills {
  /** If this card can be your commander in the Brawl format. */
  brawl: boolean;

  /** If this card can be your commander in the Commander/EDH format. */
  commander: boolean;

  /** If this card can be your commander in the Oathbreaker format. */
  oathbreaker: boolean;
}
